config/routes.rb
Text::Application.routes.draw do
  resources :errors

  resources :sub_topics

  resources :topics

  resources :passages

  resources :questions

  resources :answers

  resources :images

   root :to => 'questions#preview'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_one :image
  belongs_to :sub_topic
  belongs_to :topic
  belongs_to :passage
end

app/controllers/questions_controller.rb
require 'fileutils'
require 'tokenizer'
require 'rubygems'
require 'pdf-reader'
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def parse()

    dir_files = Array.new
    path = params[:path]
    pdf_path = params[:pdf_path]
    txt_path = params[:txt_path]
    @dir_id = params[:dir_id]
    system("unoconv -fpdf /#{path}")
    Dir.chdir("/home/satsahib/office/text/app/assets/images/my_images")
    d = Dir.new("/home/satsahib/office/text/app/assets/images/my_images")
    d.each { |file|
      dir_files << file
    }
    if dir_files.include?(@dir_id)
      require 'fileutils'
      FileUtils.rm_rf "#{@dir_id}"
      FileUtils.mkdir "/home/satsahib/office/text/app/assets/images/my_images/#{@dir_id}"
      system("pdfimages -j /#{pdf_path} /home/satsahib/office/text/app/assets/images/my_images/#{@dir_id}/")
    else
      FileUtils.mkdir "/home/satsahib/office/text/app/assets/images/my_images/#{@dir_id}"
      system("pdfimages -j /#{pdf_path} /home/satsahib/office/text/app/assets/images/my_images/#{@dir_id}/")
    end

    reader = PDF::Reader.new("/#{pdf_path}")
    file_path = "/#{txt_path}"
    reader.pages.each do |page|
      File.open(file_path, "a") { |f| f.write(page.text)
        f.write("\n")}
    end
    #opening the file in the read mode
    file = File.open("#{txt_path}", "r")
    @cfi = 0
    while (line = file.gets)
      option = line.strip
      #regular expression for various parsers
      question_pattern1 =  /^\{?\[?\(?\:?[Q0-9-\*#\.\t]+[\)\]\/\.\}:]+[ \t]*[^\n]*$/
      question_pattern2 = /^\{?\[?\(?\:?[Q]+[\s]+[0-9-\*#\.\t]+[\)\]\/\.\}:]+[ \t]*[^\n]*$/
      question_pattern3 = /^\{?\[?\(?\:?[Q0-9]+[\s]+[\)\]\/\.\}:]+[ \t]*[^\n]*$/
      option_pattern =    /^\{?\[?\(?\:?[A-Ea-e-\*#\.\t]+[\)\]\/\.\}:]+[ \t]*[^\n]*$/
      correct_pattern = /^(Ans:|Answer:|Ans :|Answer :)+[ \t]*[^\n]*$/
      topic_pattern = /^(Topic:|topic:|topic :|Topic :)+[ \t]*[^\n]*$/
      sub_topic_pattern = /^(Sub-Topic:|Sub-topic:|sub-topic:|sub-Topic:|Sub-Topic :|Sub-topic :|sub-topic :|sub-Topic :)+[ \t]*[^\n]*$/
      tag_pattern = /^(Tags:|tags:|Tags :|tags :)+[ \t]*[^\n]*$/
      marks_pattern = /^(Marks:|marks:|Marks :|marks :)+[ \t]*[^\n]*$/
      direction_pattern = /^(Directions:|directions:|direction:|Direction:|Direction :|direction :|Directions :|directions :)+[ \t]*[^\n]*$/
      image_pattern = /^(<img>)$/
      passage_pattern = /^Passage:+[ \t]*[^\n]*$/
      roman_number_pattern = /^\{?\[?\(?\:?+(?i:(?=[MDCLXVI])((M{0,3})((C[DM])|(D?C{0,3}))?((X[LC])|(L?XX{0,2})|L)?((I[VX])|(V?(II{0,2}))|V)?))+[\)\]\/\.\}:]+[ \t]*[^\n]*$$/
      @to_pattern=""
      @to_pattern1=""
      @to_pattern2=""
      @to_pattern3=""
      @to_pattern4=""
      @to_pattern5=""

      #Different parsers being used
      if topic_pattern.match(option)
        topic_parser(option)
      elsif image_pattern.match(option)
        parser_image(option,@dir_id)
      elsif direction_pattern.match(option)
        @is_passage_question = false
        direction_parser(option)
      elsif marks_pattern.match(option)
        marks_parser(option)
      elsif tag_pattern.match(option)
        tag_parser(option)
      elsif sub_topic_pattern.match(option)
        subtopic_parser(option)
      elsif option_pattern.match(option)
        option_parser(option)
      elsif passage_pattern.match(option)
        passage_parser(option)
      elsif question_pattern1.match(option) or question_pattern2.match(option) or question_pattern3.match(option)
        question_parser(option)
        if (@m_d == "t") and (@is_passage_question == true)
          if @direction_diff > 0
            save_multi_direction_of_passage_and_question_type_for_vijay()
            @direction_diff = @direction_diff - 1
          end

        elsif (@m_d == "t") and (@is_passage_question == false)

          if @direction_diff > 0
            save_multi_direction_for_vijay()
            @direction_diff = @direction_diff - 1
          end

        elsif @m_d == "f"
          save_single_direction_for_vijay()
          @direction_single=""
        else
          save_no_direction_for_vijay()
        end

      elsif correct_pattern.match(option)
        correct_pattern_parser(option)
      else
        if @recent_pattern == "q"
          @concat_question = @recent_question_pattern + " " + option
          save_concat_question_for_vijay()
        elsif @recent_pattern == "a"
          @recent_pattern_option = @recent_pattern_option+" "+ option
          save_concat_answer_for_vijay()
        elsif @recent_pattern == "p"
          @recent_pattern_passage = @recent_pattern_passage+"\n"+option
          save_concat_passage_for_vijay()
        elsif @recent_pattern == "md"
          @recent_pattern_multi_direction = @recent_pattern_multi_direction+" "+option
          save_md_for_vijay()
        elsif @recent_pattern == "sd"
          @recent_pattern_single_direction = @recent_pattern_single_direction+" "+option
          save_sd_for_vijay()
        else
          error = Error.new
          error.name = option
          error.save
        end

      end
    end
    FileUtils.rm txt_path
    FileUtils.rm pdf_path
    FileUtils.rm path
    redirect_to :action => :index
  end

  def tokenize_option(question,a,b,c,d,e)
    #to update the question table attribute "ans_status" to "ans"
    save_ans_status_to_ans_for_vijay(question)
    if !a.nil?
      aa = a.strip
    end
    if !b.nil?
      bb = b.strip
    end
    if !c.nil?
      cc = c.strip
    end
    if !d.nil?
      dd = d.strip
    end
    if !e.nil?
      ee = e.strip
    end
    tokenizer = Tokenizer::Tokenizer.new
    op = Answer.find_all_by_question_id(question.id)
    correct_count = 0
    op.each do |o|
      opt = o.answer
      to = tokenizer.tokenize(opt)
      if to[0]== aa or to[1]==aa
        ans = Answer.find(o.id)
        save_status_correct_for_option_vijay(ans)
        correct_count = correct_count + 1
      end

      if to[0]== bb or to[1]==bb
        ans = Answer.find(o.id)
        save_status_correct_for_option_vijay(ans)
        correct_count = correct_count + 1
      end

      if to[0]== cc or to[1]==cc
        ans = Answer.find(o.id)
        save_status_correct_for_option_vijay(ans)
        correct_count = correct_count + 1
      end

      if to[0]== dd or to[1]==dd
        ans = Answer.find(o.id)
        save_status_correct_for_option_vijay(ans)
        correct_count = correct_count + 1
      end

      if to[0]== ee or to[1]==ee
        ans = Answer.find(o.id)
        save_status_correct_for__option_vijay(ans)
        correct_count = correct_count + 1
      end

    end

    if (correct_count == 1) and (question.passage_id.nil?)
      save_question_type_mcq_for_vijay(question)

    elsif (correct_count > 1 ) and (question.passage_id.nil?)
      save_question_type_maq_for_vijay(question)
    end

  end

  def save_fib_with_multiple_option(que,opt1,opt2,opt3)
    #to update the question table attribute "ans_status" to "ans"
    save_ans_status_of_save_for_vijay(que)
    fib_check = /___*/

    if fib_check.match(que.question) and (que.passage_id.nil?)
      save_question_type_fib_for_vijay(que)
    end

    if !opt1.nil?
      answer = Answer.new
      answer.answer = opt1
      answer.question_id = que.id
      answer.status = "correct"
      answer.save
    end

    if !opt2.nil?
      answer.update_attribute(:answer,opt1 + ","+ opt2)
    end

    if !opt3.nil?
      answer.update_attribute(:answer,opt1 + ","+opt2 + ","+ opt3)
    end
  end




  def save_sa_tff(que,ans)
    #to update the question table attribute "ans_status" to "ans"
    save_ans_status_of_save_for_vijay(que)
    fib_check = /___*/

    if fib_check.match(que.question) and (que.passage_id.nil?)
      save_question_type_fib_for_vijay(que)
    elsif  (que.passage_id.nil?)
      save_question_type_sa_for_vijay(que)
    end

    answer = Answer.new
    answer.answer = ans[0]
    answer.question_id = que.id
    answer.status = "correct"
    answer.save
  end

  def image_parser(dir_id)
    #this parser goes to the directory where the images are getting saved and take each file and delete
    #the ". , .." files of the directory.
    image_files = Array.new
    #Giving the path of the directory where the images being saved.
    d = Dir.new("/home/satsahib/office/text/app/assets/images/my_images/#{dir_id}/")
    d.each { |file|
      image_files << file
    }
    image_files.delete(".")
    image_files.delete("..")
    return image_files
  end

  def topic_parser(opt)

    #16th march written match data for Topic:
    #1st feb 2012 Matching the topic  pattern and storing it in the topics table
    deleted_topic = opt.slice!("Topic: ")
    deleted_topic = opt.slice!("Topic:")
    deleted_topic = opt.slice!("topic:")
    deleted_topic = opt.slice!("topic :")
    deleted_topic = opt.slice!("Topic : ")
    deleted_topic1 = opt.strip
    if deleted_topic1.empty?
      @topic = Topic.new
      @topic.topic = "Unknown"
      @topic.save
    else
      topic_parser_save_vijay(deleted_topic1)
    end

  end



  def marks_parser(opt)
    deleted_marks = opt.slice!("Marks: ")
    deleted_marks = opt.slice!("marks:")
    deleted_marks = opt.slice!("Marks : ")
    deleted_marks = opt.slice!("marks :")
    deleted_marks1 = opt.strip
    @marks_tag = deleted_marks1.split(',')
  end

  def tag_parser(opt)
    #this parser gets the parses the tags which are given
    # by the user for difficulty, positive_id, negative_id
    deleted_tag = opt.slice!("Tags: ")
    deleted_tag = opt.slice!("tags:")
    deleted_tag = opt.slice!("Tags : ")
    deleted_tag = opt.slice!("tags :")
    deleted_tag1 = opt.strip
    deleted_tag2 = deleted_tag1.split(',')
    difficulty = deleted_tag2[0]
    positive_id = deleted_tag2[1]
    negative_id = deleted_tag2[2]
    tag_parser_save_vijay(difficulty, positive_id, negative_id)
  end

  def question_bank_parser(opt)
    deleted_question_bank = opt.slice!("Question-bank:")

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Question</legend>

    <div class="control-group">
      <%= f.label :question, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :question, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :topic_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :topic_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :subtopic_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :sub_topic_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :direction, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :direction, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :positive_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :positive_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :negative_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :negative_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :difficulty_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :difficulty_id, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :passage_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :passage_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :question_type, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :question_type, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :ans_status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :ans_status, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', questions_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/questions/edit.html.erb
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Question</th>
      <th>Direction</th>
      <th>Difficulty</th>
      <th>Question Type</th>
      <th>Answer Status</th>
      <th>Positive Marks</th>
      <th>Negative Marks</th>
      <th>Topic_id</th>
      <th>Subtopic_id</th>
      <th>Passage_id</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= link_to question.question, question_path(question) %></td>
        <td><%= question.direction %></td>
        <td><%= question.difficulty_id %></td>
        <td><%= question.question_type %></td>
        <td><%= question.ans_status %></td>
        <td><%= question.positive_id %></td>
        <td><%= question.negative_id %></td>
        <td><%= question.topic_id %></td>
        <td><%= question.sub_topic_id %></td>
        <td><%= question.passage_id %></td>
        <td>
          <%= link_to 'Edit', edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', question_path(question), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New', new_question_path, :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%= render :partial => 'form' %>

app/views/questions/preview.erb
<h1>Displaying Preview</h1>
<table border="1">
  <% already_displayed_topic_name=""
  already_displayed_subtopic_name=""%>
  <% for question in @questions %>
    <% if already_displayed_topic_name != question.topic.topic  %>
      <tr>
        <td>
          <%=h question.topic.topic %>
        </td>
      </tr>
      <%already_displayed_topic_name = question.topic.topic %>
    <%end%>
    <% if already_displayed_subtopic_name != question.sub_topic.subtopic  %>
      <tr>
        <td>
          <%=h question.sub_topic.subtopic %>
        </td>
      </tr>
      <%already_displayed_subtopic_name = question.sub_topic.subtopic %>
    <%end%>
    <tr>
      <td><br/>
        <b>Direction: <%=h question.direction %><br/></b>
        <% unless question.passage.nil? or question.passage.blank? %>
            <%=h question.passage.passage %><br/><br/>
          <%end%>
        <b><%=h question.question %></b><br/>
        <% unless question.image.nil? or question.image.blank? %>
          <img alt="me" src="<%= question.image.path %>" height="100" width="150"></img>
        <% end %>
      </td>
    </tr>
    <% for answer in question.answers
      if answer.status == "correct"%>
        <tr>
          <td style="color: green"><%=h answer.answer %><br/><% unless answer.image.nil? or answer.image.blank? %><img alt="me" src="<%= answer.image.path %>" height="100" width="150"></img><% end %></td>
        </tr>
      <%else%>
        <tr>
          <td><%=h answer.answer %><br/><% unless answer.image.nil? or answer.image.blank? %><img alt="me" src="<%= answer.image.path %>" height="100" width="150"></img><% end %></td>
        </tr>
      <%end%>
    <% end %>
    <tr>
      <td style="color: red">Question Type: <%=h question.question_type%></td>
    </tr>
  <% end %>
</table>

app/views/questions/save_questions.erb
<form accept-charset="UTF-8" action="/questions/parse/1" enctype="multipart/form-data" method="post">
  <b>File_path</b><br/>
  <input type="text" name="path" value="<%=@path%>"/><br/>
  <b>Pdf_path</b><br/>
  <input type="text" name="pdf_path" value="<%=@pdf_path%>"/><br/>
  <b>Text_path</b><br/>
  <input type="text" name="txt_path" value="<%=@txt_path%>"/><br/>
  <b>Directory Unique id</b><br/>
  <input type="text" name="dir_id" value="<%=@dir_id%>"/><br/>
  <div class="start_parsing"> Click On Start to Parse the Document<br/></div>
  <div class="add_btn"><input type="submit" value="Start"/></div>
</form>

app/views/questions/show.html.erb
<h1>/Question</h1>

<p>
  <b>Question</b><br>
  <%= @question.question %>
</p>

<p>
  <b>Topic</b><br>
  <%= @question.topic_id %>
</p>

<p>
  <b>Subtopic</b><br>
  <%= @question.sub_topic_id %>
</p>

<p>
  <b>Direction</b><br>
  <%= @question.direction %>
</p>

<p>
  <b>Positive</b><br>
  <%= @question.positive_id %>
</p>

<p>
  <b>Negative</b><br>
  <%= @question.negative_id %>
</p>

<p>
  <b>Difficulty</b><br>
  <%= @question.difficulty_id %>
</p>

<p>
  <b>Passage</b><br>
  <%= @question.passage_id %>
</p>

<p>
  <b>Question type</b><br>
  <%= @question.question_type %>
</p>

<p>
  <b>Ans status</b><br>
  <%= @question.ans_status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', questions_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_question_path(@question), :class => 'btn' %>
  <%= link_to 'Delete', question_path(@question), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/questions/upload_questions.erb
<form accept-charset="UTF-8" action="/questions/save_questions/1" enctype="multipart/form-data" method="post">
      Add questions from a doc file<br/>
      <input type="file" name="question" value="" size="45" /><br/>
      Enter the directory name for storing the image.<br/>
      <input type="text" name="surupa_id"/><br/>
       <input type="submit" value="Add Doc File" />
</form>