config/routes.rb
Text::Application.routes.draw do
  resources :errors

  resources :sub_topics

  resources :topics

  resources :passages

  resources :questions

  resources :answers

  resources :images

   root :to => 'questions#preview'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :questions
  has_many :sub_topics
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Topic</legend>

    <div class="control-group">
      <%= f.label :topic, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :topic, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', topics_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Topic</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.id %></td>
        <td><%= link_to topic.topic, topic_path(topic) %></td>
        <td>
          <%= link_to 'Edit', edit_topic_path(topic), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', topic_path(topic), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_topic_path, :class => 'btn btn-primary' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<h1>/Topic</h1>

<p>
  <b>Topic</b><br>
  <%= @topic.topic %>
</p>

<div class="form-actions">
  <%= link_to 'Back', topics_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_topic_path(@topic), :class => 'btn' %>
  <%= link_to 'Delete', topic_path(@topic), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>