config/routes.rb
Text::Application.routes.draw do
  resources :errors

  resources :sub_topics

  resources :topics

  resources :passages

  resources :questions

  resources :answers

  resources :images

   root :to => 'questions#preview'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_one :image
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Answer</legend>

    <div class="control-group">
      <%= f.label :answer, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :answer, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :question_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :question_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :status, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', answers_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/answers/edit.html.erb
<%= render :partial => 'form' %>

app/views/answers/index.html.erb
<h1>Answers</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Answer</th>
      <th>Status</th>
      <th>Question_id</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.id %></td>
        <td><%= link_to answer.answer, answer_path(answer) %></td>
        <td><%= answer.status %></td>
        <td><%= answer.question_id %></td>
        <td>
          <%= link_to 'Edit', edit_answer_path(answer), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', answer_path(answer), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_answer_path, :class => 'btn btn-primary' %>

app/views/answers/new.html.erb
<%= render :partial => 'form' %>

app/views/answers/show.html.erb
<h1>/Answer</h1>

<p>
  <b>Answer</b><br>
  <%= @answer.answer %>
</p>

<p>
  <b>Question</b><br>
  <%= @answer.question_id %>
</p>

<p>
  <b>Status</b><br>
  <%= @answer.status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', answers_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_answer_path(@answer), :class => 'btn' %>
  <%= link_to 'Delete', answer_path(@answer), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>