config/routes.rb
Text::Application.routes.draw do
  resources :errors

  resources :sub_topics

  resources :topics

  resources :passages

  resources :questions

  resources :answers

  resources :images

   root :to => 'questions#preview'
  

   match ':controller(/:action(/:id))(.:format)'
end

app/models/passage.rb
class Passage < ActiveRecord::Base
  has_many :questions
end

app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  # GET /passages
  # GET /passages.json
  def index
    @passages = Passage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @passages }
    end
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
    @passage = Passage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/new
  # GET /passages/new.json
  def new
    @passage = Passage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @passage }
    end
  end

  # GET /passages/1/edit
  def edit
    @passage = Passage.find(params[:id])
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(params[:passage])

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render json: @passage, status: :created, location: @passage }
      else
        format.html { render action: "new" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /passages/1
  # PUT /passages/1.json
  def update
    @passage = Passage.find(params[:id])

    respond_to do |format|
      if @passage.update_attributes(params[:passage])
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage = Passage.find(params[:id])
    @passage.destroy

    respond_to do |format|
      format.html { redirect_to passages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/passages_helper.rb
module PassagesHelper
end

app/views/passages/_form.html.erb
<%= form_for @passage, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Passage</legend>

    <div class="control-group">
      <%= f.label :passage, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :passage, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', passages_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/passages/edit.html.erb
<%= render :partial => 'form' %>

app/views/passages/index.html.erb
<h1>Passages</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Passage</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.id %></td>
        <td><%= link_to passage.passage, passage_path(passage) %></td>
        <td>
          <%= link_to 'Edit', edit_passage_path(passage), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', passage_path(passage), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_passage_path, :class => 'btn btn-primary' %>

app/views/passages/new.html.erb
<%= render :partial => 'form' %>

app/views/passages/show.html.erb
<h1>/Passage</h1>

<p>
  <b>Passage</b><br>
  <%= @passage.passage %>
</p>

<div class="form-actions">
  <%= link_to 'Back', passages_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_passage_path(@passage), :class => 'btn' %>
  <%= link_to 'Delete', passage_path(@passage), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>